In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
train_df=pd.read_csv(r"D:\Machine Learning A-Z Template Folder\Part 8 - Deep Learning\Section 39 - Artificial Neural Networks (ANN)\Churn_Modelling.csv")

In [3]:
train_df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X=train_df.iloc[:,3:-1]

In [5]:
y=train_df.iloc[:,13:14]

In [6]:
state=pd.get_dummies(X["Geography"],drop_first=True)

In [7]:
gender=pd.get_dummies(X["Gender"],drop_first=True)

In [8]:
X=X.drop(["Geography","Gender"],axis=1)

In [9]:
X=pd.concat([X,state,gender],axis=1)

In [10]:
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0               1        101348.88        0      0     0  
1               1        112542.58        0      1     0  
2               0        113931.57        0      0     0  
3               0         93826.63        0      0     0  
4               1         79084.10        0      1     0

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [63]:
X_train.shape

(8000, 11)

In [14]:
import keras

Using TensorFlow backend.


In [15]:
#initialize the layers
from keras.layers import Dense

## Initializing the ANN

In [16]:
#initialize the neural network
from keras.models import Sequential
from keras.layers import Dropout

In [17]:
classifier=Sequential()

W1208 11:14:12.561445 16516 deprecation_wrapper.py:119] From C:\Users\prasanna\.conda\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [18]:
# adding no of hidden layer


In [19]:
#droup out are added to neurons
#we actualy use it avoid overfitting
#Dropout(rate, noise_shape=None, seed=None, **kwargs)
#rate :fraction of input units to drop
#      suppose we have 10 neurons the,10% in 10 is 1 and we drop 1 neuron 

In [64]:
classifier.add(Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform"))
classifier.add(Dropout(rate=0.1))

In [65]:
# adding second hidden layer
classifier.add(Dense(activation="relu", units=6, kernel_initializer="uniform"))
classifier.add(Dropout(rate=0.1))

In [66]:
# adding the output layer
#replace rectifier function relu to sigmoid function
classifier.add(Dense(activation="sigmoid", units=1, kernel_initializer="uniform"))

In [23]:
#compiling the ANN
#adam : one of the stochastic gradient function
#loss : binary_crossentropy for binary outcome
#       categorical_crossentropy for multiple outcomes
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

W1208 11:14:13.317430 16516 deprecation_wrapper.py:119] From C:\Users\prasanna\.conda\envs\tensorflow\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W1208 11:14:13.386274 16516 deprecation_wrapper.py:119] From C:\Users\prasanna\.conda\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W1208 11:14:13.395213 16516 deprecation.py:323] From C:\Users\prasanna\.conda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


## Fit ANN to the training set


In [24]:
#batch_size:update the values only after n of oberservations (Batch learning)
#epoch: its is actually the no of times the whole data set has passed
classifier.fit(X_train,y_train,batch_size=7,nb_epoch=50)

C:\Users\prasanna\.conda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  This is separate from the ipykernel package so we can avoid doing imports until


Epoch 1/50
8000/8000 [==============================] - 4s 518us/step - loss: 0.4708 - acc: 0.7959
Epoch 2/50
8000/8000 [==============================] - 3s 342us/step - loss: 0.4334 - acc: 0.7960
Epoch 3/50
8000/8000 [==============================] - 3s 338us/step - loss: 0.4291 - acc: 0.7960
Epoch 4/50
8000/8000 [==============================] - 3s 367us/step - loss: 0.4273 - acc: 0.8061
Epoch 5/50
8000/8000 [==============================] - 3s 335us/step - loss: 0.4234 - acc: 0.8209
Epoch 6/50
8000/8000 [==============================] - 3s 336us/step - loss: 0.4237 - acc: 0.8226
Epoch 7/50
8000/8000 [==============================] - 3s 336us/step - loss: 0.4251 - acc: 0.8276
Epoch 8/50
8000/8000 [==============================] - 3s 335us/step - loss: 0.4247 - acc: 0.8270
Epoch 9/50
8000/8000 [==============================] - 3s 335us/step - loss: 0.4239 - acc: 0.8270
Epoch 10/50
8000/8000 [==============================] - 3s 366us/step - loss: 0.4255 - acc: 0.8275
Epoch 11/

In [25]:
#predict the probabilities
y_pred=classifier.predict(X_test)
y_pred=pd.DataFrame(y_pred)
y_pred=y_pred.rename(columns={0:'y_pred'})

In [26]:
y_pred.head()

y_pred
0  0.266637
1  0.307963
2  0.140605
3  0.059974
4  0.228418

In [27]:
#convert the predicted values as true or false
y_pred=(y_pred>0.5)
#if the probability is greater than 0.5 then the customer is more likely to leave the bank

In [28]:
y_pred.head(10)

y_pred
0   False
1   False
2   False
3   False
4   False
5    True
6   False
7   False
8   False
9    True

In [29]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [30]:
cm

array([[1559,   36],
       [ 286,  119]], dtype=int64)

In [79]:
(1559+119)/2000

0.839

In [31]:
# Assignment

In [32]:
X.columns

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Germany', 'Spain', 'Male'],
      dtype='object')

In [33]:
train_=pd.DataFrame({'CreditScore':[600],
                     'Age':[40],
                     'Tenure':[3],
                     'Balance':[60000],
                     'NumOfProducts':[2],
                     'HasCrCard':[1],
                     'IsActiveMember':[1],
                     'EstimatedSalary':[50000],
                     'German':[0],
                     'Spain':[0],
                     'Male':[1]
                    })

In [34]:
train_

CreditScore  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          600   40       3    60000              2          1   

   IsActiveMember  EstimatedSalary  German  Spain  Male  
0               1            50000       0      0     1

In [35]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
train_=sc.fit_transform(train_)

In [36]:
y_pred_train=classifier.predict(train_)

In [37]:
y_pred_train=(y_pred_train>0.5)

In [38]:
y_pred_train

array([[False]])

What is the need to evaluate the model and perform k fold cross validation ?
ans:The way we performed train test split as in above is not             recommendable b'cause the train test split of data is done by       selecting the rows randomly

 # Tuning the model

In [57]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

from keras.models import Sequential
from keras.layers import Dense, Activation, Embedding, Flatten, LeakyReLU, BatchNormalization, Dropout
from keras.activations import relu, sigmoid


In [58]:
def create_model(layers, activation):
    model = Sequential()
    for i, nodes in enumerate(layers):
        if i==0:
            model.add(Dense(nodes,input_dim=X_train.shape[1]))
            model.add(Activation(activation))
            model.add(Dropout(0.3))
        else:
            model.add(Dense(nodes))
            model.add(Activation(activation))
            model.add(Dropout(0.3))
            
    model.add(Dense(units = 1, kernel_initializer= 'glorot_uniform', activation = 'sigmoid')) # Note: no activation beyond this point
    
    model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])
    return model
    
model = KerasClassifier(build_fn=create_model, verbose=0)

In [59]:
layers = [[20], [40, 20], [45, 30, 15]]
activations = ['sigmoid', 'relu']
param_grid = dict(layers=layers, activation=activations, batch_size = [128, 256], epochs=[30])


In [60]:
grid = GridSearchCV(estimator=model, param_grid=param_grid,cv=5)



In [61]:
grid_result = grid.fit(X_train, y_train)

[grid_result.best_score_,grid_result.best_params_]

[0.856375,
 {'activation': 'relu', 'batch_size': 128, 'epochs': 30, 'layers': [40, 20]}]

In [73]:
#predict the probabilities
y_pred=grid.predict(X_test)
y_pred=pd.DataFrame(y_pred)
y_pred=y_pred.rename(columns={0:'y_pred'})

In [74]:
#convert the predicted values as true or false
y_pred=(y_pred>0.5)
#if the probability is greater than 0.5 then the customer is more likely to leave the bank

In [75]:
y_pred.head()

y_pred
0   False
1   False
2   False
3   False
4   False

In [76]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [77]:
cm

array([[1547,   48],
       [ 214,  191]], dtype=int64)

In [78]:
(1547+191)/2000

0.869